CREATE TABLE User (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Hash VARCHAR(400) NOT NULL,
    Salt VARCHAR(30) NOT NULL,
    TeamId INT NOT NULL REFERENCES Team(Id)
);